swagger: "2.0"

info:
  version: 0.1.0
  title: Online
  description: Yakit Online Service

schemes:
  - http

basePath: /api

consumes:
  - application/json

produces:
  - application/json

securityDefinitions:
  user:
    type: apiKey
    in: header
    name: Authorization
  trusted:
    type: apiKey
    in: header
    name: Authorization

security:
  - user: [ ]

paths:
  /auth/from-github/callback:
    get:
      security: [ ]
      parameters:
        - in: query
          type: string
          name: code
      responses:
        200:
          $ref: "#/responses/ActionSucceeded"
  /auth/from-github:
    get:
      security: [ ]
      parameters: [ ]
      responses:
        200:
          description: "Fetch Github Oauth URL"
          schema:
            type: string
  /user/fetch:
    get:
      parameters:
        - in: query
          type: integer
          name: id
      responses:
        200:
          description: "查询 User 记录"
          schema:
            $ref: "#/definitions/User"
  /user:
    get:
      security:
        - trusted: [ ]
      parameters:
        - $ref: "#/parameters/Page"
        - $ref: "#/parameters/Order"
        - $ref: "#/parameters/Limit"
        - $ref: "#/parameters/OrderBy"
        - in: query
          type: string
          name: name
      responses:
        200:
          description: "查询 User 记录"
          schema:
            $ref: "#/definitions/UsersResponse"
    delete:
      security:
        - trusted: [ ]
      parameters:
        - in: query
          name: id
          type: integer
      responses:
        200:
          $ref: "#/responses/ActionSucceeded"
  /user/tags:
    get:
      parameters: [ ]
      responses:
        200:
          description: "查询 /user  所有的Tags"
          schema:
            type: array
            items:
              type: string
    post:
      parameters:
        - in: query
          type: integer
          name: id
          required: true
        - in: query
          type: string
          enum:
            - add
            - set
          name: op
        - in: query
          type: array
          items:
            type: string
          name: tags
      responses:
        200:
          $ref: "#/responses/ActionSucceeded"
  /operation:
    get:
      parameters:
        - $ref: "#/parameters/Page"
        - $ref: "#/parameters/Order"
        - $ref: "#/parameters/Limit"
        - $ref: "#/parameters/OrderBy"
        - in: query
          type: string
          name: name
      responses:
        200:
          description: "查询 Operation 记录"
          schema:
            $ref: "#/definitions/OperationsResponse"
    post:
      parameters:
        - in: body
          name: Data
          schema:
            $ref: "#/definitions/NewOperation"
      responses:
        200:
          $ref: "#/responses/ActionSucceeded"
    delete:
      parameters:
        - in: query
          name: id
          type: integer
      responses:
        200:
          $ref: "#/responses/ActionSucceeded"
  /yakit/plugin/fetch:
    get:
      parameters:
        - in: query
          type: integer
          name: id
      responses:
        200:
          description: "查询 YakitPlugin 记录"
          schema:
            $ref: "#/definitions/YakitPlugin"
  /yakit/plugin:
    get:
      parameters:
        - $ref: "#/parameters/Page"
        - $ref: "#/parameters/Order"
        - $ref: "#/parameters/Limit"
        - $ref: "#/parameters/OrderBy"
        - in: query
          type: string
          name: name
      responses:
        200:
          description: "查询 YakitPlugin 记录"
          schema:
            $ref: "#/definitions/YakitPluginsResponse"
    post:
      parameters:
        - in: body
          name: Data
          schema:
            $ref: "#/definitions/NewYakitPlugin"
      responses:
        200:
          $ref: "#/responses/ActionSucceeded"
    delete:
      parameters:
        - in: query
          name: id
          type: integer
      responses:
        200:
          $ref: "#/responses/ActionSucceeded"
  /yakit/plugin/tags:
    get:
      parameters: [ ]
      responses:
        200:
          description: "查询 /yakit/plugin  所有的Tags"
          schema:
            type: array
            items:
              type: string
    post:
      parameters:
        - in: query
          type: integer
          name: id
          required: true
        - in: query
          type: string
          enum:
            - add
            - set
          name: op
        - in: query
          type: array
          items:
            type: string
          name: tags
      responses:
        200:
          $ref: "#/responses/ActionSucceeded"

responses:
  ActionSucceeded:
    description: API 调用成功
    schema:
      $ref: '#/definitions/ActionSucceeded'
  ActionFailed:
    description: API 调用失败
    schema:
      $ref: '#/definitions/ActionFailed'

parameters:
  Page:
    name: page
    in: query
    type: integer
    default: 1
  Limit:
    name: limit
    type: integer
    in: query
    default: 20
  OrderBy:
    name: order_by
    type: string
    in: query
  Order:
    name: order
    type: string
    in: query
    default: "desc"
    enum:
      - asc
      - desc

definitions:
  UsersResponse:
    allOf:
      - $ref: "#/definitions/Paging"
    required:
      - data
    properties:
      data:
        type: array
        items:
          $ref: "#/definitions/User"
  User:
    allOf:
      - $ref: "#/definitions/GormBaseModel"
      - $ref: "#/definitions/NewUser"
  NewUser:
    type: object
    required:
      - uesr_unique_id
      - user_verbose
      - from_platform
      - trusted
      - tags
    properties:
      tags:
        type: array
        items:
          type: string
      uesr_unique_id:
        type: string
      user_verbose:
        type: string
      from_platform:
        type: string
      trusted:
        type: boolean
      email:
        type: string
  OperationsResponse:
    allOf:
      - $ref: "#/definitions/Paging"
    required:
      - data
    properties:
      data:
        type: array
        items:
          $ref: "#/definitions/Operation"
  Operation:
    allOf:
      - $ref: "#/definitions/GormBaseModel"
      - $ref: "#/definitions/NewOperation"
  NewOperation:
    type: object
    required:
      - type
      - trigger_user_unique_id
      - operation_plugin_id
    properties:
      type:
        type: string
      trigger_user_unique_id:
        type: string
      operation_plugin_id:
        type: string
      extra:
        type: string
  YakitPluginsResponse:
    allOf:
      - $ref: "#/definitions/Paging"
    required:
      - data
    properties:
      data:
        type: array
        items:
          $ref: "#/definitions/YakitPlugin"
  YakitPlugin:
    allOf:
      - $ref: "#/definitions/GormBaseModel"
      - $ref: "#/definitions/NewYakitPlugin"
  YakitPluginParam:
    type: object
    required:
      - field
    properties:
      field:
        type: string
      default_value:
        type: string
      type_verbose:
        type: string
      field_verbose:
        type: string
      help:
        type: string
      required:
        type: boolean
      group:
        type: string
  NewYakitPlugin:
    type: object
    required:
      - type
      - script_name
      - authors
      - content
      - published_at
      - tags
      - is_official
      - default_open
    properties:
      default_open:
        type: boolean
      is_official:
        type: boolean
      tags:
        type: array
        items:
          type: string
      params:
        type: array
        items:
          $ref: "#/definitions/YakitPluginParam"
      type:
        type: string
      script_name:
        type: string
      authors:
        type: array
        items:
          type: string
      content:
        type: string
      published_at:
        type: integer
        description: "插件发布的时间"
      downloaded_total:
        type: integer
        description: "下载次数"
      stars:
        type: integer
        description: "获得推荐的次数"
      forks:
        type: integer
        description: "被修改的次数"
  Paging:
    type: object
    required:
      - pagemeta
    properties:
      pagemeta:
        $ref: "#/definitions/PageMeta"
  ActionFailed:
    type: object
    required:
      - from
      - ok
      - reason
    properties:
      from:
        type: string
        description: 来源于哪个 API
      ok:
        type: boolean
        description: 执行状态
      reason:
        type: string
  ActionSucceeded:
    type: object
    required:
      - from
      - ok
    properties:
      from:
        type: string
        description: 来源于哪个 API
      ok:
        type: boolean
        description: 执行状态
  PageMeta:
    type: object
    description: 描述分页信息的元信息
    required:
      - page
      - limit
      - total
      - total_page
    properties:
      page:
        type: integer
        description: 页面索引
        default: 1
      limit:
        type: integer
        description: 页面数据条数限制
        default: 20
      total:
        type: integer
        description: 总共数据条数
      total_page:
        type: integer
        description: 总页数
        default: 1
  GormBaseModel:
    type: object
    required:
      - id
      - created_at
      - updated_at
    properties:
      id:
        type: integer
      created_at:
        type: integer
      updated_at:
        type: integer
  Principle:
    type: object
    required:
      - user
    properties:
      user:
        type: string
